[package]
name = "board-game"
version = "0.3.5"
authors = ["Karel Peeters <karel.peeters.leuven@gmail.com>"]
description = "A board game abstraction and generic utilities around it."
license = "MIT OR Apache-2.0"
edition = "2018"
keywords = ["board", "ai", "ataxx", "sttt"]
categories = ["algorithms", "games"]
repository = "https://github.com/KarelPeeters/board-game-rs"

[dependencies]
rand = { version = "0.8.4", features = ["small_rng"] }
itertools = "0.10.1"
rayon = "1.5.1"
decorum = { version = "0.3.1", default-features = false, features = ["std"] }
internal-iterator = "0.1.2"
num = "0.4.0"
nom = "7.0.0"
regex = { version = "1.5.4", default-features = false, features = ["std"] }
rand_xoshiro = "0.6.0"
cast_trait = "0.1.2"
chess = "3.2.0"

# temporary fix until https://github.com/jordanbray/chess/pull/67 is merged
[profile.dev.build-override]
opt-level = 3
[profile.release.build-override]
opt-level = 3
[profile.test.build-override]
opt-level = 3